extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false']
  indentation:
    spaces: 2
  document-start: disable
  comments:
    min-spaces-from-content: 1

ignore: |
  cli/ui/pnpm-lock.yaml
  web/package-lock.json
  **/node_modules/
  plans/**/*.md
