blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/d-oit/do-web-doc-resolover/discussions
    about: Please ask and answer general questions here.
